version: '3.8'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - movie-app

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=movie-db
      - DB_USER=admin
      - DB_PASSWORD=pass
      - DATABASE_URL=postgresql://admin:pass@postgres-db:5433/movie-db?schema=public"

    networks:
      - movie-app

  database:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=movie-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - movie-app

networks:
  movie-app:
    driver: bridge
volumes:
  postgres-data: