version: '3.8'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - movie-app

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - SALT=${SALT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public

    networks:
      - movie-app

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    networks:
      - movie-app

networks:
  movie-app:
    driver: bridge

