version: '3.8'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - movie-app

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=TEST_DB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/TEST_DB?schema=public

    networks:
      - movie-app

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_DB
    restart: unless-stopped
    networks:
      - movie-app

networks:
  movie-app:
    driver: bridge

