"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.httpServer = void 0;
var express_1 = require("express");
var body_parser_1 = require("body-parser");
var cors_1 = require("cors");
var http_1 = require("http");
var error_1 = require("./middewares/error");
var route_1 = require("./routes/route");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: false }));
app.use(route_1.mainRouter);
app.use(error_1.handleError);
exports.default = app;
exports.httpServer = (0, http_1.createServer)(app);
