"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.reviewRouter = void 0;
var express_1 = require("express");
var controller_1 = require("./controller");
var router = (0, express_1.Router)();
exports.reviewRouter = router;
router.post("/reviews", controller_1.createReview);
router.get("/reviews", controller_1.getReviews);
router.get("/reviews/:reviewId", controller_1.getReviewById);
router.post("/reviews/:reviewId", controller_1.updateReviewById);
router.delete("/reviews/:reviewId", controller_1.deleteReviewById);
